### ISSUE TITLE
chemozart.com is down :/

### ISSUE THREAD

**Issue by q2apro** [mohebifar/chemozart#3]
It would be great if https://chemozart.com would be up again. It's a fantastic tool that I just recently discovered!

Please bring it back. Thanks!

**Comment by jparkhill** [comment]
You might wanna try out https://www.atomsandbits.ai/
It provides similar optimization facilities. (although it doesn't have a builder) for that use Avogadro.

**Comment by mohebifar** [comment]
@q2apro It is back up now. Sorry for the inconvenience.

**Comment by q2apro** [comment]
@jparkhill I like to use a tool *without* registration.

Such as https://chemozart.com/ and http://molview.org

@mohebifar Thanks!!

**Comment by Immortalin** [comment]
Chemozart and atomandbits are down again.
